spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wyjaxtechblog?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: wjdrl12

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.Type: trace